language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - composer validate
  - vendor/bin/phpcs
  - ./bin/php-doc-check -d ./ --exclude vendor/